Здесь мы получаем данные из общей таблицы данных

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import pandas as pd
from dotenv import load_dotenv, find_dotenv
from sqlalchemy import create_engine

In [4]:
# подгружаем .env
load_dotenv()

True

In [5]:
# Считываем все креды
src_host = os.environ.get('DB_SOURCE_HOST')
src_port = os.environ.get('DB_SOURCE_PORT')
src_username = os.environ.get('DB_SOURCE_USER')
src_password = os.environ.get('DB_SOURCE_PASSWORD')
src_db = os.environ.get('DB_SOURCE_NAME') 

dst_host = os.environ.get('DB_DESTINATION_HOST')
dst_port = os.environ.get('DB_DESTINATION_PORT')
dst_username = os.environ.get('DB_DESTINATION_USER')
dst_password = os.environ.get('DB_DESTINATION_PASSWORD')
dst_db = os.environ.get('DB_DESTINATION_NAME')

s3_bucket = os.environ.get('S3_BUCKET_NAME')
s3_access_key = os.environ.get('AWS_ACCESS_KEY_ID')
s3_secret_access_key = os.environ.get('AWS_SECRET_ACCESS_KEY')

In [6]:
# Создадим соединения
src_conn = create_engine(f'postgresql://{src_username}:{src_password}@{src_host}:{src_port}/{src_db}')
dst_conn = create_engine(f'postgresql://{dst_username}:{dst_password}@{dst_host}:{dst_port}/{dst_db}')

In [12]:
TABLE = 'data_combined'
SQL = f'select * from {TABLE}'
data = pd.read_sql(SQL, dst_conn)
data

,flat_id,building_id,floor,kitchen_area,living_area,rooms,is_apartment,studio,total_area,price,build_year,building_type_int,latitude,longitude,ceiling_height,flats_count,floors_total,has_elevator,target
0,0,6220,9,9.90,19.900000,1,False,False,35.099998,9500000,1965,6,55.717113,37.781120,2.64,84,12,True,9500000
1,1,18012,7,0.00,16.600000,1,False,False,43.000000,13500000,2001,2,55.794849,37.608013,3.00,97,10,True,13500000
2,2,17821,9,9.00,32.000000,2,False,False,56.000000,13500000,2000,4,55.740040,37.761742,2.70,80,10,True,13500000
3,3,18579,1,10.10,43.099998,3,False,False,76.000000,20000000,2002,4,55.672016,37.570877,2.64,771,17,True,20000000
4,4,9293,3,3.00,14.000000,1,False,False,24.000000,5200000,1971,1,55.808807,37.707306,2.60,208,9,True,5200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141357,141357,22455,16,11.00,18.000000,1,False,False,42.000000,10500000,2013,4,55.626579,37.313503,2.64,672,25,True,10500000
141358,141358,3162,5,5.28,28.330000,2,False,False,41.110001,7400000,1960,1,55.727470,37.768677,2.48,80,5,False,7400000
141359,141359,6513,7,5.30,20.000000,1,False,False,31.500000,9700000,1966,4,55.704315,37.506584,2.64,72,9,True,9700000
141360,141360,23952,15,13.80,33.700001,2,False,False,65.300003,11750000,2017,4,55.699863,37.939564,2.70,480,25,True,11750000
141361,141361,15104,16,7.60,18.000000,1,False,False,38.000000,8000000,1988,4,55.862133,37.689613,2.74,128,17,True,8000000

In [10]:
with pd.option_context("display.max_columns", 2):
    display(data)

        flat_id  ...    target
0             0  ...   9500000
1             1  ...  13500000
2             2  ...  13500000
3             3  ...  20000000
4             4  ...   5200000
...         ...  ...       ...
141357   141357  ...  10500000
141358   141358  ...   7400000
141359   141359  ...   9700000
141360   141360  ...  11750000
141361   141361  ...   8000000

[141362 rows x 19 columns]

А дальше, творите!